spring:
  web:
    resources:
      static-locations: file:src/main/resources/static/
  application:
    name: aviatickets
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://dpg-cp6u4vacn0vc73a15n5g-a:5432/aviatickets_01p7"
    hikari:
      username: aviatickets_01p7_user
      password: srZAUIgXL7mPMkp0K8V07fOd0ZZdk0v9
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT}
